#
# C Unit Test example  
#

### Module settings ###

LONGNAME   = example 
NAME       = example
VERSION    = 0.1.0
TYPE       = exe

### Project configuration ###
include $(COMPENV)/mk/config.mk

### Module overrides ###
MAKEFILE   = makefile

LIBS = cutest

#the next line must be commented if no debug print

### Variant overrides ###

### Project targets ###
include $(COMPENV)/mk/targets.mk
