#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = glib component library
NAME     = glib
VERSION  = 2.21.6-19
TYPE     = none

PUBINCFOLDERS = .

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBLIBS  = $(LIBFOLDER)/libgio-2.0.so
PUBLIBS += $(LIBFOLDER)/libgio-2.0.so.0
PUBLIBS += $(LIBFOLDER)/libgio-2.0.so.0.2106.0
PUBLIBS += $(LIBFOLDER)/libglib-2.0.so
PUBLIBS += $(LIBFOLDER)/libglib-2.0.so.0
PUBLIBS += $(LIBFOLDER)/libglib-2.0.so.0.2106.0
PUBLIBS += $(LIBFOLDER)/libgmodule-2.0.so
PUBLIBS += $(LIBFOLDER)/libgmodule-2.0.so.0
PUBLIBS += $(LIBFOLDER)/libgmodule-2.0.so.0.2106.0
PUBLIBS += $(LIBFOLDER)/libgobject-2.0.so
PUBLIBS += $(LIBFOLDER)/libgobject-2.0.so.0
PUBLIBS += $(LIBFOLDER)/libgobject-2.0.so.0.2106.0
PUBLIBS += $(LIBFOLDER)/libgthread-2.0.so
PUBLIBS += $(LIBFOLDER)/libgthread-2.0.so.0
PUBLIBS += $(LIBFOLDER)/libgthread-2.0.so.0.2106.0

# include project targets 
include $(COMPENV)/mk/targets.mk
