#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = libcurl
NAME     = libcurl
VERSION  = 7.25.0
TYPE     = none

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBINCFOLDERS = .
PUBLIBS  = $(wildcard $(LIBFOLDER)/*.*)

# include project targets 
include $(COMPENV)/mk/targets.mk

