#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = libxml2
NAME     = libxml2
VERSION  = 2.7.8
TYPE     = none

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBINCFOLDERS = .
PUBLIBS  = $(wildcard $(LIBFOLDER)/*.*)

# include project targets 
include $(COMPENV)/mk/targets.mk

