/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#ifndef _DRMTEESUPPORTED_H_
#define _DRMTEESUPPORTED_H_ 1

#include <drmteetypes.h>
#include <oemteetypes.h>

ENTER_PK_NAMESPACE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_AES128CTR_IMPL_IsAES128CTRSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_DOM_IMPL_IsDOMSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_H264_IMPL_IsH264Supported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_LICGEN_IMPL_IsLICGENSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_LICPREP_IMPL_IsLICPREPSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_LPROV_IMPL_IsLPROVSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_PRNDRX_IMPL_IsPRNDRXSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_PRNDTX_IMPL_IsPRNDTXSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_RPROV_IMPL_IsRPROVSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_REVOCATION_IMPL_IsREVOCATIONSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_SAMPLEPROT_IMPL_IsSAMPLEPROTSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_SECURESTOP_IMPL_IsSECURESTOPSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_SIGN_IMPL_IsSIGNSupported( DRM_VOID ) DRM_NO_INLINE_ATTRIBUTE;

EXIT_PK_NAMESPACE;

#endif /* _DRMTEESUPPORTED_H_ */

