#
# C Unit Test Library 
#

### Module settings ###

LONGNAME   = cutest
NAME       = cutest
VERSION    = 0.1.0
TYPE       = lib

### Project configuration ###
include $(COMPENV)/mk/config.mk

### Module overrides ###
MAKEFILE   = makefile

WARNFLAGS = -W -Wall

DEFINES += DPRLEVEL=4000

PUBINCFOLDERS = cutest

### Project targets ###
include $(COMPENV)/mk/targets.mk
