#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = Command line application for libgphoto2
NAME     = gphoto2
VERSION  = 2.4.10
TYPE     = none

BINFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-bin

CPFILES = $(BINFOLDER)/gphoto2
CPFILES_DEST = $(notdir $(DEST))/bin

# include project targets 
include $(COMPENV)/mk/targets.mk
