#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = libusb 1.0
NAME     = libusb
VERSION  = 1.0.8
TYPE     = none

PUBINCFOLDERS = libusb-1.0

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBLIBS  = $(LIBFOLDER)/libusb-1.0.a
PUBLIBS += $(LIBFOLDER)/libusb-1.0.la
PUBLIBS += $(LIBFOLDER)/libusb-1.0.so
PUBLIBS += $(LIBFOLDER)/libusb-1.0.so.0
PUBLIBS += $(LIBFOLDER)/libusb-1.0.so.0.0.0

# include project targets 
include $(COMPENV)/mk/targets.mk
