#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = libjpeg
NAME     = libjpeg
VERSION  = 8.4.0
TYPE     = none

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBINCFOLDERS = ljpeg
PUBLIBS  = $(wildcard $(LIBFOLDER)/*.*)

# include project targets 
include $(COMPENV)/mk/targets.mk

