#
# Loewe Module Makefile
# 

# include projects defaults
include $(COMPENV)/mk/config.mk


# name of makefile
MAKEFILE = makefile

# module configuration
LONGNAME = sqlite3 library
NAME     = sqlite3
VERSION  = 3.7.13
TYPE     = lib

PUBINCFOLDERS = .

# include project targets
include $(COMPENV)/mk/targets.mk

