#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = Command line parser
NAME     = libpopt
VERSION  = 1.14
TYPE     = none

PUBINCFOLDERS = .

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBLIBS  = $(LIBFOLDER)/libpopt.so
PUBLIBS += $(LIBFOLDER)/libpopt.so.0
PUBLIBS += $(LIBFOLDER)/libpopt.so.0.0.0

# include project targets 
include $(COMPENV)/mk/targets.mk
