#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = user space file system for libgphoto2
NAME     = gphotofs
VERSION  = 0.4.0
TYPE     = none

BINFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-bin

CPFILES = $(BINFOLDER)/gphotofs
CPFILES_DEST = $(notdir $(DEST))/bin

# include project targets 
include $(COMPENV)/mk/targets.mk
