#
# Loewe Module Makefile
#

# include project defaults
include $(COMPENV)/mk/config.mk

# Module Configuration
LONGNAME = oauth authentication library
NAME     = liboauth
VERSION  = 0.8.8
TYPE     = none

PUBINCFOLDERS = oauth

LIBFOLDER= $(COMPENV_TARGET_MACHINE)-$(COMPENV_TARGET_OS)-lib

PUBLIBS  = $(LIBFOLDER)/liboauth.so
PUBLIBS += $(LIBFOLDER)/liboauth.so.0
PUBLIBS += $(LIBFOLDER)/liboauth.so.0.6.0

# include project targets 
include $(COMPENV)/mk/targets.mk
